name: Echo Workflow
on: workflow_dispatch
jobs:
  idenfity-job:
    runs-on: ubuntu-latest
    steps:
      - name: Greeting
        run: echo "Welcome to echo Workflow"
      - name: Collecting environment
        run: |
          cat /proc/self/cgroup
          echo '---'
          whoami
          echo '---'
          echo "$PATH"
          echo '---'
          pwd
          echo '---'
          printenv
      - name: End of Greeting
        run: echo "Thank you, enjoy!"
